import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { hasMasterSessionFromRequest } from "@/lib/master-auth";
import { getPracticeAmountPaise } from "@/lib/pricing";

type SettingStatus = "configured" | "missing" | "optional" | "warning";

type SettingItem = {
  id: string;
  label: string;
  description: string;
  status: SettingStatus;
  value: string;
  envKey?: string;
};

type SettingGroup = {
  id: string;
  title: string;
  description: string;
  items: SettingItem[];
};

function isSet(value: string | undefined | null) {
  const trimmed = value?.trim() ?? "";
  if (!trimmed) return false;
  const lower = trimmed.toLowerCase();
  return !(
    lower.startsWith("replace-with") ||
    lower.startsWith("change-me") ||
    lower.includes("xxxxx") ||
    lower.startsWith("your_") ||
    lower.includes("project_ref")
  );
}

function maskSecret(value: string | undefined | null) {
  const trimmed = value?.trim() ?? "";
  if (!trimmed) return "Not set";
  if (trimmed.length <= 4) return "••••";
  return `${trimmed.slice(0, 4)}••••`;
}

function razorpayMode() {
  const keyId = process.env.RAZORPAY_KEY_ID?.trim() ?? process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID?.trim() ?? "";
  if (!keyId) return "Not configured";
  return keyId.startsWith("rzp_live_") ? "Live" : "Test";
}

export async function GET(request: Request) {
  if (!hasMasterSessionFromRequest(request)) {
    return NextResponse.json({ error: "Unauthorized." }, { status: 401 });
  }

  try {
    let databaseStatus: SettingStatus = "missing";
    let databaseValue = "Unreachable";
    try {
      await prisma.$queryRaw`SELECT 1`;
      databaseStatus = "configured";
      databaseValue = "Connected";
    } catch {
      databaseStatus = "missing";
      databaseValue = "Connection failed";
    }

    const practiceBasePrice = Number(process.env.PRACTICE_BASE_PRICE_RUPEES);
    const practicePriceRupees =
      Number.isFinite(practiceBasePrice) && practiceBasePrice > 0 ? practiceBasePrice : 50;
    const sample10MinPrice = getPracticeAmountPaise(10) / 100;

    const videoProvider = process.env.VIDEO_STORAGE_PROVIDER?.trim().toLowerCase() || "local";
    const emailProvider = process.env.EMAIL_PROVIDER?.trim().toLowerCase() || "smtp";
    const smtpConfigured = isSet(process.env.SMTP_HOST);
    const openAiConfigured = isSet(process.env.OPENAI_API_KEY);
    const razorpayConfigured =
      isSet(process.env.RAZORPAY_KEY_ID) &&
      isSet(process.env.RAZORPAY_KEY_SECRET) &&
      isSet(process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID);
    const masterEmailConfigured =
      isSet(process.env.MASTER_ADMIN_EMAIL) && isSet(process.env.MASTER_ADMIN_PASSWORD);
    const companySessionConfigured =
      isSet(process.env.COMPANY_SESSION_SECRET) || isSet(process.env.ADMIN_PORTAL_KEY);

    const groups: SettingGroup[] = [
      {
        id: "platform",
        title: "Platform",
        description: "Public URLs and core runtime flags used across marketing, invites, and redirects.",
        items: [
          {
            id: "app-url",
            label: "App URL",
            description: "Base URL for links generated by the app (NEXT_PUBLIC_APP_URL).",
            status: isSet(process.env.NEXT_PUBLIC_APP_URL) ? "configured" : "warning",
            value: process.env.NEXT_PUBLIC_APP_URL?.trim() || "http://localhost:3000 (default)",
            envKey: "NEXT_PUBLIC_APP_URL",
          },
          {
            id: "invite-base-url",
            label: "Invite email base URL",
            description: "Production domain used inside candidate invite emails.",
            status: isSet(process.env.INVITE_EMAIL_BASE_URL) ? "configured" : "optional",
            value: process.env.INVITE_EMAIL_BASE_URL?.trim() || "Falls back to app URL",
            envKey: "INVITE_EMAIL_BASE_URL",
          },
          {
            id: "node-env",
            label: "Runtime environment",
            description: "Development vs production behaviour for cookies, email, and security.",
            status: "configured",
            value: process.env.NODE_ENV ?? "development",
          },
          {
            id: "database",
            label: "Database",
            description: "PostgreSQL connection via Prisma (DATABASE_URL / DIRECT_URL).",
            status: databaseStatus,
            value: databaseValue,
            envKey: "DATABASE_URL",
          },
        ],
      },
      {
        id: "auth",
        title: "Authentication & sessions",
        description: "Login credentials and cookie signing for master admin and company portals.",
        items: [
          {
            id: "master-email-login",
            label: "Master admin email login",
            description: "Email + password used on /master-login.",
            status: masterEmailConfigured ? "configured" : "warning",
            value: masterEmailConfigured
              ? process.env.MASTER_ADMIN_EMAIL?.trim() ?? "Configured"
              : "Set MASTER_ADMIN_EMAIL and MASTER_ADMIN_PASSWORD",
            envKey: "MASTER_ADMIN_EMAIL",
          },
          {
            id: "master-key",
            label: "Master admin API key",
            description: "Legacy key login and session signing fallback.",
            status: isSet(process.env.MASTER_ADMIN_KEY) ? "configured" : "warning",
            value: maskSecret(process.env.MASTER_ADMIN_KEY),
            envKey: "MASTER_ADMIN_KEY",
          },
          {
            id: "company-session",
            label: "Company admin sessions",
            description: "Encrypts company admin cookies after /company-login.",
            status: companySessionConfigured ? "configured" : "missing",
            value: companySessionConfigured ? "Secret configured" : "Set COMPANY_SESSION_SECRET or ADMIN_PORTAL_KEY",
            envKey: "COMPANY_SESSION_SECRET",
          },
        ],
      },
      {
        id: "ai",
        title: "AI & scoring",
        description: "OpenAI-powered interviews, rubric scoring, and embeddings.",
        items: [
          {
            id: "openai",
            label: "OpenAI API",
            description: "Required for live interviews, scoring, and question generation.",
            status: openAiConfigured ? "configured" : "missing",
            value: openAiConfigured ? maskSecret(process.env.OPENAI_API_KEY) : "Not configured",
            envKey: "OPENAI_API_KEY",
          },
          {
            id: "scoring-model",
            label: "Scoring model",
            description: "Model used when generating scorecards after interviews.",
            status: isSet(process.env.SCORING_MODEL) ? "configured" : "optional",
            value: process.env.SCORING_MODEL?.trim() || "gpt-4.1-mini (default)",
            envKey: "SCORING_MODEL",
          },
          {
            id: "scoring-mode",
            label: "Scoring mode",
            description: "Rubric-based vs other scoring strategies.",
            status: "configured",
            value: process.env.SCORING_MODE?.trim() || "rubric",
            envKey: "SCORING_MODE",
          },
          {
            id: "embedding-model",
            label: "Embedding model",
            description: "Used for semantic answer evaluation when enabled.",
            status: isSet(process.env.EMBEDDING_MODEL) ? "configured" : "optional",
            value: process.env.EMBEDDING_MODEL?.trim() || "text-embedding-3-small (default)",
            envKey: "EMBEDDING_MODEL",
          },
        ],
      },
      {
        id: "payments",
        title: "Payments (Practice)",
        description: "Razorpay checkout for self-serve practice interviews on /practice.",
        items: [
          {
            id: "razorpay",
            label: "Razorpay gateway",
            description: "Key ID, secret, and public key for checkout + verification.",
            status: razorpayConfigured ? "configured" : "missing",
            value: razorpayConfigured ? `${razorpayMode()} mode` : "Not configured",
            envKey: "RAZORPAY_KEY_ID",
          },
          {
            id: "razorpay-webhook",
            label: "Razorpay webhook secret",
            description: "Validates payment webhooks from Razorpay.",
            status: isSet(process.env.RAZORPAY_WEBHOOK_SECRET) ? "configured" : "optional",
            value: isSet(process.env.RAZORPAY_WEBHOOK_SECRET) ? "Configured" : "Optional for dev",
            envKey: "RAZORPAY_WEBHOOK_SECRET",
          },
          {
            id: "practice-price",
            label: "Practice base price",
            description: `₹${practicePriceRupees} per 10-minute slot. A 10-min session costs ₹${sample10MinPrice}.`,
            status: isSet(process.env.PRACTICE_BASE_PRICE_RUPEES) ? "configured" : "optional",
            value: `₹${practicePriceRupees} / 10 min`,
            envKey: "PRACTICE_BASE_PRICE_RUPEES",
          },
        ],
      },
      {
        id: "email",
        title: "Email delivery",
        description: "Candidate invites, contact form replies, and transactional mail.",
        items: [
          {
            id: "email-provider",
            label: "Email provider",
            description: "SMTP or AWS SES for outbound email.",
            status: smtpConfigured || emailProvider === "ses" ? "configured" : "missing",
            value: emailProvider.toUpperCase(),
            envKey: "EMAIL_PROVIDER",
          },
          {
            id: "smtp-host",
            label: "SMTP host",
            description: "Mail server hostname (GoDaddy, Mailtrap, SES SMTP, etc.).",
            status: smtpConfigured ? "configured" : "missing",
            value: process.env.SMTP_HOST?.trim() || "Not set",
            envKey: "SMTP_HOST",
          },
          {
            id: "smtp-from",
            label: "From address",
            description: "Sender shown to candidates and admins.",
            status: isSet(process.env.SMTP_FROM_EMAIL) ? "configured" : "optional",
            value:
              process.env.SMTP_FROM?.trim() ||
              process.env.SMTP_FROM_EMAIL?.trim() ||
              "Not set",
            envKey: "SMTP_FROM_EMAIL",
          },
          {
            id: "support-email",
            label: "Support / reply-to",
            description: "Monitored inbox for deliverability and user replies.",
            status: isSet(process.env.SUPPORT_EMAIL) ? "configured" : "optional",
            value: process.env.SUPPORT_EMAIL?.trim() || "Not set",
            envKey: "SUPPORT_EMAIL",
          },
        ],
      },
      {
        id: "storage",
        title: "Video & file storage",
        description: "Where interview recordings and uploads are stored.",
        items: [
          {
            id: "video-provider",
            label: "Video storage provider",
            description: "Local disk for dev; S3 or Supabase for production.",
            status: "configured",
            value: videoProvider === "s3" ? "S3 / cloud" : "Local filesystem",
            envKey: "VIDEO_STORAGE_PROVIDER",
          },
          {
            id: "s3-bucket",
            label: "AWS S3 bucket",
            description: "Required when VIDEO_STORAGE_PROVIDER=s3.",
            status:
              videoProvider === "s3"
                ? isSet(process.env.AWS_S3_BUCKET) && isSet(process.env.AWS_ACCESS_KEY_ID)
                  ? "configured"
                  : "missing"
                : "optional",
            value: process.env.AWS_S3_BUCKET?.trim() || "Not required for local",
            envKey: "AWS_S3_BUCKET",
          },
          {
            id: "supabase-storage",
            label: "Supabase storage bucket",
            description: "Alternative cloud storage via Supabase.",
            status:
              isSet(process.env.SUPABASE_URL) && isSet(process.env.SUPABASE_SERVICE_ROLE_KEY)
                ? "configured"
                : "optional",
            value: process.env.SUPABASE_STORAGE_BUCKET?.trim() || "uhired-videos (default)",
            envKey: "SUPABASE_STORAGE_BUCKET",
          },
        ],
      },
    ];

    const allItems = groups.flatMap((group) => group.items);
    const configuredCount = allItems.filter((item) => item.status === "configured").length;
    const missingCount = allItems.filter((item) => item.status === "missing").length;
    const warningCount = allItems.filter((item) => item.status === "warning").length;

    return NextResponse.json({
      summary: {
        configuredCount,
        missingCount,
        warningCount,
        optionalCount: allItems.filter((item) => item.status === "optional").length,
        totalChecks: allItems.length,
        healthPct: Math.round((configuredCount / Math.max(1, allItems.length)) * 1000) / 10,
        environment: process.env.NODE_ENV ?? "development",
        appUrl: process.env.NEXT_PUBLIC_APP_URL?.trim() || "http://localhost:3000",
      },
      groups,
      notes: [
        "Most settings are controlled via server environment variables (.env locally, hosting dashboard in production).",
        "Secret values are never shown in full — only configuration status and safe display values.",
        "After changing .env, restart the server for changes to take effect.",
      ],
    });
  } catch {
    return NextResponse.json({ error: "Unable to load system settings." }, { status: 500 });
  }
}
