/** Role → skills mapping for PDF scorecards. More specific entries must appear first in the array. */

export type RoleCatalogEntry = {
  id: string;
  label: string;
  patterns: RegExp[];
  skills: string[];
  matchKeywords: RegExp;
};

function r(
  id: string,
  label: string,
  patterns: string[],
  skills: string[],
  matchKeywords: string,
): RoleCatalogEntry {
  return {
    id,
    label,
    patterns: patterns.map((p) => new RegExp(p, "i")),
    skills,
    matchKeywords: new RegExp(matchKeywords, "i"),
  };
}

export const ROLE_CATALOG: RoleCatalogEntry[] = [
  // --- IT / Software (specific before generic) ---
  r("blockchain-developer", "Blockchain Development", ["blockchain developer", "blockchain engineer", "web3 developer", "smart contract developer"], ["Smart Contracts", "Blockchain Fundamentals", "Solidity / Web3", "Security Best Practices", "DApp Development", "Communication"], "blockchain|web3|solidity|smart contract|crypto|ethereum|dapp"),
  r("iot-developer", "IoT Development", ["iot developer", "internet of things", "iot engineer", "embedded iot"], ["Embedded Systems", "Sensors & Hardware", "IoT Protocols", "Firmware", "Cloud Integration", "Communication"], "iot|internet of things|sensor|mqtt|embedded|firmware|device"),
  r("embedded-engineer", "Embedded Engineering", ["embedded engineer", "embedded developer", "firmware engineer", "embedded software"], ["C / Embedded C", "Microcontrollers", "RTOS", "Hardware Interfaces", "Debugging", "Communication"], "embedded|firmware|microcontroller|rtos|hardware|mcu|arm"),
  r("game-developer", "Game Development", ["game developer", "game programmer", "unity developer", "unreal developer"], ["Game Engines", "Gameplay Programming", "Physics & Graphics", "Performance Optimization", "Debugging", "Communication"], "game|unity|unreal|gamedev|gameplay|3d|graphics"),
  r("erp-developer", "ERP Development", ["erp developer", "sap consultant", "oracle erp", "dynamics erp", "erp implementation"], ["ERP Modules", "Business Processes", "Configuration", "Integration", "Testing", "Communication"], "erp|sap|oracle|dynamics|module|implementation|enterprise"),
  r("crm-developer", "CRM Development", ["crm developer", "salesforce developer", "hubspot developer", "crm consultant"], ["CRM Platforms", "Workflow Automation", "Integrations", "Data Management", "Customization", "Communication"], "crm|salesforce|hubspot|zoho|pipeline|lead|customer"),
  r("qa-engineer", "QA / Testing", ["qa engineer", "test engineer", "quality assurance engineer", "software tester", "automation tester", "sdet"], ["Test Planning", "Manual Testing", "Automation", "Bug Reporting", "Regression Testing", "Communication"], "qa|test|testing|selenium|cypress|junit|bug|quality assurance|sdet"),
  r("dba", "Database Administration", ["database administrator", "\\bdba\\b", "database engineer", "sql dba"], ["SQL & Tuning", "Backup & Recovery", "Performance Optimization", "Security & Access", "High Availability", "Communication"], "dba|database admin|sql server|oracle|postgres|mysql|backup|replication"),
  r("sysadmin", "System Administration", ["system administrator", "sysadmin", "it administrator", "systems engineer"], ["OS Administration", "Server Maintenance", "Monitoring", "Backup & Recovery", "Security Hardening", "Communication"], "sysadmin|system admin|linux|windows server|active directory|patch"),
  r("network-engineer", "Network Engineering", ["network engineer", "network administrator", "network architect"], ["Routing & Switching", "Firewalls", "VPN / DNS", "Troubleshooting", "Network Security", "Communication"], "network|cisco|routing|switching|firewall|vpn|dns|lan|wan"),
  r("technical-support-engineer", "Technical Support", ["technical support engineer", "it support engineer", "support engineer", "desktop support"], ["Troubleshooting", "Product Knowledge", "Ticketing Systems", "Documentation", "Customer Communication", "Escalation"], "technical support|it support|helpdesk|troubleshoot|ticket|desktop support"),
  r("mobile-developer", "Mobile App Development", ["mobile app developer", "android developer", "ios developer", "flutter developer", "react native"], ["Mobile UI Development", "Android / iOS SDKs", "API Integration", "App Performance", "Debugging", "Communication"], "mobile|android|ios|flutter|swift|kotlin|react native"),
  r("web-developer", "Web Development", ["web developer", "frontend developer", "backend developer", "full stack developer", "full-stack developer", "mern", "mern stack"], ["HTML / CSS / JS", "React", "Node.js", "MongoDB", "REST APIs", "Express.js"], "web|frontend|backend|html|css|javascript|react|api|mongodb|node|express|mern"),
  r("devops", "DevOps / Cloud", ["devops engineer", "devops", "site reliability", "sre", "cloud engineer", "platform engineer"], ["CI/CD Pipelines", "Docker / Kubernetes", "Cloud Infrastructure", "Monitoring", "Incident Response", "Communication"], "devops|ci/cd|docker|kubernetes|aws|azure|gcp|terraform|pipeline"),
  r("data-scientist", "Data Science / AI", ["data scientist", "machine learning engineer", "ai engineer", "ml engineer", "deep learning"], ["Python / ML Stack", "Data Modeling", "Statistics", "Feature Engineering", "Model Evaluation", "Communication"], "data science|machine learning|ml|ai|python|model|neural|tensorflow|pytorch"),
  r("software-developer", "Software Development", ["software developer", "software engineer", "programmer", "application developer", "\\bsde\\b"], ["Programming Fundamentals", "System Design", "Debugging", "Code Quality", "APIs & Databases", "Communication"], "software|developer|programming|code|api|database|git|java|python"),
  r("cybersecurity", "Cyber Security", ["cyber security", "cybersecurity", "information security", "security analyst", "penetration tester", "soc analyst"], ["Threat Analysis", "Network Security", "Incident Response", "Vulnerability Assessment", "Security Policies", "Communication"], "security|cyber|threat|vulnerability|firewall|soc|penetration"),

  // --- Medical ---
  r("surgeon", "Surgery / Medical", ["surgeon", "surgical", "operation theatre", "ot technician"], ["Surgical Knowledge", "Procedure Planning", "Patient Safety", "Clinical Decision Making", "Emergency Handling", "Communication"], "surg|operation|ot|scalpel|theatre"),
  r("pharmacist", "Pharmacy", ["pharmacist", "pharmacy", "chemist"], ["Pharmacology", "Prescription Accuracy", "Drug Interactions", "Inventory Management", "Patient Counseling", "Communication"], "pharma|drug|prescription|medicine|dispens"),
  r("physiotherapist", "Physiotherapy", ["physiotherapist", "physical therapist", "physio"], ["Anatomy & Mobility", "Treatment Planning", "Rehabilitation", "Patient Assessment", "Exercise Therapy", "Communication"], "physio|therapy|rehab|mobility|exercise"),
  r("lab-technician", "Medical Laboratory", ["lab technician", "laboratory technician", "pathology lab", "medical lab"], ["Sample Handling", "Lab Equipment", "Test Procedures", "Quality Control", "Safety Protocols", "Documentation"], "lab|laboratory|pathology|sample|specimen|test"),
  r("nursing", "Nursing", ["registered nurse", "staff nurse", "licensed practical nurse", "\\brn\\b", "\\blpn\\b", "nurse practitioner", "\\bnursing\\b", "\\bnurse\\b"], ["Patient Care", "Clinical Assessment", "Medication Safety", "Care Documentation", "Infection Control", "Communication"], "nurs|patient|clinical|medication|bedside|ward"),
  r("doctor", "Medical / Doctor", ["\\bdoctor\\b", "physician", "medical officer", "general practitioner", "\\bmbbs\\b"], ["Clinical Reasoning", "Diagnosis", "Treatment Planning", "Medical Ethics", "Emergency Response", "Communication"], "medical|clinical|patient|diagnos|treatment|physician"),

  // --- Engineering ---
  r("chemical-engineer", "Chemical Engineering", ["chemical engineer", "chemical engineering", "process engineer"], ["Chemical Processes", "Process Safety", "Plant Operations", "Quality Control", "Technical Analysis", "Communication"], "chemical|process|reactor|plant|hazop"),
  r("automobile-engineer", "Automobile Engineering", ["automobile engineer", "automotive engineer", "vehicle engineer"], ["Vehicle Systems", "CAD Design", "Manufacturing", "Quality Testing", "Diagnostics", "Communication"], "automobile|automotive|vehicle|car|chassis"),
  r("civil-engineer", "Civil Engineering", ["civil engineer", "structural engineer", "site engineer", "construction engineer", "geotechnical"], ["Structural Analysis", "AutoCAD / Civil 3D", "Site Planning", "Building Codes", "Quantity Estimation", "Communication"], "civil|structural|construction|concrete|survey|autocad|bim"),
  r("mechanical-engineer", "Mechanical Engineering", ["mechanical engineer", "hvac engineer", "thermal engineer"], ["Mechanical Design", "Thermodynamics", "CAD / SolidWorks", "Manufacturing", "Quality Control", "Communication"], "mechanical|hvac|thermal|cad|solidworks|machine"),
  r("electrical-engineer", "Electrical Engineering", ["electrical engineer", "electronics engineer", "power systems"], ["Circuit Design", "Power Systems", "Control Systems", "Safety Standards", "Troubleshooting", "Communication"], "electrical|circuit|power|voltage|electronics|plc"),

  // --- Education ---
  r("principal", "School Leadership", ["\\bprincipal\\b", "school head", "headmaster", "headmistress"], ["School Administration", "Staff Leadership", "Academic Planning", "Discipline & Policy", "Stakeholder Management", "Communication"], "principal|school|administration|leadership|staff"),
  r("professor", "Higher Education", ["\\bprofessor\\b", "lecturer", "faculty", "assistant professor", "associate professor"], ["Subject Mastery", "Research", "Curriculum Design", "Student Mentoring", "Academic Assessment", "Communication"], "professor|lecturer|faculty|university|college|research"),
  r("counselor-education", "Student Counseling", ["school counselor", "student counselor", "guidance counselor", "career counselor"], ["Student Guidance", "Counseling Techniques", "Career Planning", "Communication", "Ethics", "Assessment"], "counsel|guidance|student|career|mental"),
  r("education-coordinator", "Education Coordination", ["education coordinator", "academic coordinator", "curriculum coordinator"], ["Curriculum Planning", "Academic Scheduling", "Faculty Coordination", "Assessment Design", "Compliance", "Communication"], "education|curriculum|academic|coordinator|syllabus"),
  r("teacher", "Teaching", ["\\bteacher\\b", "school teacher", "primary teacher", "secondary teacher", "tutor", "educator"], ["Subject Knowledge", "Lesson Planning", "Classroom Management", "Student Assessment", "Engagement", "Communication"], "teach|classroom|student|lesson|curriculum|school"),

  // --- Business & Management ---
  r("ceo", "Executive Leadership", ["\\bceo\\b", "chief executive", "managing director", "\\bmd\\b"], ["Strategic Vision", "Leadership", "Decision Making", "Stakeholder Management", "Business Growth", "Communication"], "ceo|executive|strategy|leadership|board|vision"),
  r("coo", "Operations Leadership", ["\\bcoo\\b", "chief operating officer", "head of operations"], ["Operations Strategy", "Process Excellence", "Team Leadership", "KPI Management", "Cross-functional Alignment", "Communication"], "coo|operating officer|operations strategy|execution|scale"),
  r("cto", "Technology Leadership", ["\\bcto\\b", "chief technology officer", "head of engineering", "vp engineering"], ["Technology Strategy", "Architecture", "Team Leadership", "Innovation", "Security & Scale", "Communication"], "cto|technology strategy|engineering leadership|architecture|innovation"),
  r("cfo", "Financial Leadership", ["\\bcfo\\b", "chief financial officer", "finance director"], ["Financial Strategy", "Budgeting", "Risk Management", "Compliance", "Reporting", "Communication"], "cfo|finance|budget|treasury|audit|risk"),
  r("entrepreneur", "Entrepreneurship", ["\\bentrepreneur\\b", "business owner", "founder", "co-founder", "startup founder"], ["Business Vision", "Strategy", "Sales & Marketing", "Finance Basics", "Leadership", "Communication"], "entrepreneur|founder|startup|business owner|venture|scale"),
  r("strategy-consultant", "Strategy Consulting", ["strategy consultant", "management consultant", "business consultant", "strategy advisor"], ["Business Analysis", "Market Research", "Strategic Planning", "Problem Solving", "Client Presentation", "Communication"], "strategy|consulting|advisory|framework|growth|transformation"),
  r("compliance-officer", "Compliance", ["compliance officer", "regulatory compliance", "compliance manager"], ["Regulatory Knowledge", "Policy Implementation", "Risk Assessment", "Audits", "Documentation", "Communication"], "compliance|regulatory|policy|audit|governance|risk"),
  r("risk-manager", "Risk Management", ["risk manager", "enterprise risk", "risk analyst"], ["Risk Identification", "Mitigation Planning", "Compliance", "Reporting", "Stakeholder Communication", "Analysis"], "risk|mitigation|enterprise|assessment|control|exposure"),
  r("finance-manager", "Finance Management", ["finance manager", "financial controller", "head of finance"], ["Financial Planning", "Budgeting", "Reporting", "Cash Flow", "Team Management", "Communication"], "finance manager|financial planning|budget|controller|accounts|forecast"),
  r("administrative-manager", "Administration", ["administrative manager", "office manager", "admin manager", "facilities manager"], ["Office Operations", "Vendor Management", "Scheduling", "Documentation", "Team Coordination", "Communication"], "admin|office|facilities|operations|coordination|vendor"),
  r("franchise-manager", "Franchise Management", ["franchise manager", "franchise operations", "franchise development"], ["Franchise Operations", "Brand Standards", "Training", "Sales Support", "Compliance", "Communication"], "franchise|outlet|brand standards|royalty|expansion|operations"),
  r("business-development-manager", "Business Development", ["business development manager", "\\bbdm\\b", "bd manager", "partnerships manager"], ["Lead Generation", "Partnerships", "Negotiation", "Market Research", "Pipeline Management", "Communication"], "business development|partnership|bdm|pipeline|deal|expansion"),
  r("talent-acquisition", "Talent Acquisition", ["talent acquisition specialist", "talent acquisition manager", "recruitment specialist", "hiring specialist"], ["Sourcing", "Screening", "Interviewing", "Employer Branding", "ATS Tools", "Communication"], "talent acquisition|recruit|sourcing|hiring|ats|candidate"),
  r("training-manager", "Training & L&D", ["training manager", "learning and development", "l&d manager", "corporate trainer"], ["Training Design", "Facilitation", "Needs Analysis", "Learning Programs", "Evaluation", "Communication"], "training|learning|development|facilitation|l&d|workshop"),
  r("product-manager", "Product Management", ["product manager", "product owner", "associate product manager", "senior product manager"], ["Product Strategy", "Roadmap Planning", "User Research", "Prioritization", "Stakeholder Alignment", "Communication"], "product manager|product owner|roadmap|feature|backlog|prd|user story"),
  r("project-manager", "Project Management", ["project manager", "program manager", "pmo", "scrum master", "delivery manager"], ["Planning & Scheduling", "Stakeholder Management", "Risk Management", "Budget Control", "Team Leadership", "Communication"], "project|program|scrum|agile|delivery|stakeholder|timeline"),
  r("business-analyst", "Business Analysis", ["business analyst", "\\bba\\b", "product analyst", "requirements analyst"], ["Requirements Gathering", "Process Mapping", "Documentation", "Stakeholder Communication", "Solution Design", "Analysis"], "business analyst|requirements|process|stakeholder|brd|user story"),
  r("hr-manager", "Human Resources", ["hr manager", "human resources", "hr executive", "recruiter", "people operations"], ["Talent Assessment", "Employee Relations", "HR Policy", "Interviewing", "Onboarding", "Communication"], "hr|human resources|recruit|talent|employee|hiring"),
  r("customer-success-manager", "Customer Success", ["customer success manager", "customer success specialist", "client success manager"], ["Onboarding", "Retention", "Account Health", "Upsell Support", "Relationship Management", "Communication"], "customer success|retention|churn|onboarding|account health|nps"),
  r("account-manager", "Account Management", ["account manager", "key account manager", "client relationship manager"], ["Client Relationships", "Account Planning", "Renewals", "Cross-sell", "Stakeholder Management", "Communication"], "account manager|client|relationship|renewal|key account|stakeholder"),
  r("sales-manager", "Sales Management", ["sales manager", "regional sales manager", "head of sales"], ["Sales Strategy", "Team Leadership", "Forecasting", "Pipeline Management", "Negotiation", "Communication"], "sales manager|team|target|quota|forecast|pipeline"),
  r("operations-manager", "Operations Management", ["operations manager", "general manager", "plant manager"], ["Operations Planning", "Process Improvement", "Team Management", "KPI Tracking", "Vendor Coordination", "Communication"], "operations|process|kpi|plant|production|efficiency"),

  // --- Finance & Banking ---
  r("auditor", "Auditing", ["\\bauditor\\b", "audit manager", "internal audit"], ["Audit Standards", "Financial Controls", "Risk Assessment", "Compliance", "Reporting", "Communication"], "audit|auditing|compliance|controls|ifrs|gaap"),
  r("investment-banker", "Investment Banking", ["investment banker", "investment banking", "equity research"], ["Financial Modeling", "Valuation", "Market Analysis", "Deal Structuring", "Presentation", "Communication"], "investment|banking|valuation|equity|m&a|deal"),
  r("bank-manager", "Banking", ["bank manager", "branch manager", "relationship manager", "bank officer"], ["Banking Operations", "Customer Service", "Credit Assessment", "Compliance", "Sales Targets", "Communication"], "bank|branch|loan|credit|customer|nbfc"),
  r("accountant", "Accounting", ["\\baccountant\\b", "accounts executive", "chartered accountant", "\\bca\\b", "bookkeeper"], ["Accounting Standards", "Bookkeeping", "Tax & Compliance", "Reconciliation", "Financial Reporting", "Communication"], "account|bookkeep|ledger|tax|gst|tally|audit"),
  r("financial-analyst", "Financial Analysis", ["financial analyst", "finance analyst", "fp&a"], ["Financial Analysis", "Forecasting", "Excel Modeling", "Reporting", "Variance Analysis", "Communication"], "finance|financial|forecast|budget|model|analysis"),

  // --- Marketing & Sales ---
  r("affiliate-marketing", "Affiliate Marketing", ["affiliate marketing manager", "affiliate manager", "affiliate specialist"], ["Partner Recruitment", "Commission Structures", "Tracking", "Campaign Coordination", "Analytics", "Communication"], "affiliate|partner|commission|referral|tracking|payout"),
  r("influencer-marketing", "Influencer Marketing", ["influencer marketing manager", "influencer manager", "creator partnerships"], ["Influencer Outreach", "Campaign Briefs", "Contracting", "ROI Tracking", "Brand Fit", "Communication"], "influencer|creator|collaboration|partnership|reach|engagement"),
  r("email-marketing", "Email Marketing", ["email marketing specialist", "email marketing manager", "email campaign manager"], ["Email Strategy", "Copy & Design", "Automation", "List Segmentation", "A/B Testing", "Communication"], "email|newsletter|mailchimp|klaviyo|drip|automation|campaign"),
  r("sem-ppc-specialist", "SEM / PPC", ["sem specialist", "ppc specialist", "paid search specialist", "google ads specialist"], ["Google Ads", "Keyword Bidding", "Ad Copy", "Landing Pages", "ROI Optimization", "Communication"], "ppc|sem|google ads|paid search|cpc|bid|adwords"),
  r("content-marketing", "Content Marketing", ["content marketing manager", "content marketing specialist", "content strategist"], ["Content Strategy", "Editorial Calendar", "SEO Content", "Distribution", "Analytics", "Communication"], "content marketing|editorial|blog|strategy|calendar|distribution"),
  r("marketing-analyst", "Marketing Analytics", ["marketing analyst", "marketing data analyst", "digital marketing analyst"], ["Marketing Analytics", "Reporting", "Attribution", "Dashboards", "Insights", "Communication"], "marketing analytics|attribution|roi|report|dashboard|kpi|funnel"),
  r("growth-hacker", "Growth Marketing", ["growth hacker", "growth marketer", "growth manager"], ["Growth Experiments", "Funnel Optimization", "Analytics", "Acquisition", "Retention", "Communication"], "growth|experiment|funnel|acquisition|retention|hack|viral"),
  r("campaign-manager", "Campaign Management", ["campaign manager", "marketing campaign manager", "campaign specialist"], ["Campaign Planning", "Execution", "Budgeting", "Cross-channel Coordination", "Reporting", "Communication"], "campaign|launch|timeline|budget|coordination|execution"),
  r("ecommerce-marketing", "E-commerce Marketing", ["e-commerce marketing manager", "ecommerce marketing manager", "online marketing manager"], ["Online Promotions", "Conversion", "Marketplace Ads", "Product Marketing", "Analytics", "Communication"], "ecommerce marketing|online promotion|marketplace|shopify|amazon ads|conversion"),
  r("marketing-coordinator", "Marketing Coordination", ["marketing coordinator", "marketing assistant", "marketing executive"], ["Campaign Support", "Scheduling", "Vendor Coordination", "Documentation", "Team Support", "Communication"], "marketing coordinator|coordination|calendar|vendor|support|admin"),
  r("pr-manager", "Public Relations", ["public relations manager", "\\bpr manager\\b", "pr executive", "communications manager"], ["Media Relations", "Press Releases", "Crisis Communication", "Brand Reputation", "Stakeholder Outreach", "Communication"], "public relations|pr|media|press|reputation|communications"),
  r("crm-marketing-specialist", "CRM Marketing", ["crm specialist", "crm marketing", "marketing automation specialist"], ["CRM Tools", "Lead Nurturing", "Segmentation", "Automation", "Lifecycle Campaigns", "Communication"], "crm|hubspot|salesforce marketing|automation|lead|nurture|lifecycle"),
  r("community-manager", "Community Management", ["community manager", "online community manager", "community specialist"], ["Community Engagement", "Moderation", "Content", "Events", "Feedback Loops", "Communication"], "community|forum|discord|engagement|moderation|audience"),
  r("seo-specialist", "SEO", ["seo specialist", "seo executive", "\\bseo\\b", "search engine optimization"], ["Keyword Research", "On-Page SEO", "Technical SEO", "Analytics", "Content Optimization", "Communication"], "seo|search engine|keyword|ranking|backlink|serp"),
  r("social-media-manager", "Social Media", ["social media manager", "social media executive"], ["Content Planning", "Platform Management", "Engagement", "Analytics", "Brand Voice", "Communication"], "social media|instagram|facebook|linkedin|twitter|reels|stories"),
  r("digital-marketer", "Digital Marketing", ["digital marketer", "digital marketing executive", "digital marketing specialist", "digital marketing manager", "performance marketer"], ["Campaign Strategy", "Paid Ads", "Analytics", "Conversion Optimization", "Content", "Communication"], "digital|marketing|ads|ppc|google|meta|campaign|online"),
  r("brand-manager", "Brand Management", ["brand manager", "brand strategist"], ["Brand Strategy", "Market Research", "Positioning", "Campaign Planning", "Creative Briefs", "Communication"], "brand|positioning|identity|market research|campaign"),
  r("sales-executive", "Sales", ["sales executive", "sales manager", "business development", "account executive", "inside sales"], ["Prospecting", "Negotiation", "CRM", "Product Pitch", "Objection Handling", "Communication"], "sales|negotiation|crm|pipeline|prospect|revenue"),
  r("customer-support", "Customer Support", ["customer support", "customer support executive", "customer success", "call center", "help desk", "service desk"], ["Issue Resolution", "Product Knowledge", "Empathy & Tone", "Ticketing Systems", "Escalation Handling", "Communication"], "support|customer|ticket|helpdesk|resolution|service|call center"),

  // --- Design & Creative ---
  r("game-designer", "Game Design", ["game designer", "level designer", "narrative designer"], ["Game Mechanics", "Level Design", "Player Experience", "Documentation", "Prototyping", "Communication"], "game design|gameplay|level|mechanics|gdd|player experience"),
  r("vfx-artist", "VFX", ["vfx artist", "visual effects artist", "compositor"], ["Visual Effects", "Compositing", "3D Integration", "Software Tools", "Timing", "Creativity"], "vfx|visual effects|compositing|nuke|after effects|fx"),
  r("3d-artist", "3D Art", ["3d artist", "3d modeler", "3d generalist"], ["3D Modeling", "Texturing", "Lighting", "Rendering", "Software Tools", "Creativity"], "3d|modeling|maya|blender|zbrush|render|texture"),
  r("brand-identity-designer", "Brand Identity Design", ["brand identity designer", "logo designer", "identity designer"], ["Logo Design", "Brand Guidelines", "Typography", "Color Systems", "Visual Identity", "Communication"], "brand identity|logo|guidelines|identity system|mark|visual identity"),
  r("packaging-designer", "Packaging Design", ["packaging designer", "package designer"], ["Packaging Layout", "Materials", "Print Specs", "Brand Alignment", "3D Mockups", "Communication"], "packaging|label|box|print|dieline|product pack"),
  r("print-designer", "Print Design", ["print designer", "publication designer", "magazine designer"], ["Print Layout", "Typography", "Prepress", "Color Management", "Brand Consistency", "Communication"], "print|magazine|poster|brochure|prepress|publication"),
  r("industrial-designer", "Industrial Design", ["industrial designer", "product industrial designer"], ["Product Form", "Materials", "Ergonomics", "CAD / Sketching", "Prototyping", "Communication"], "industrial|product design|ergonomics|prototype|cad|physical product"),
  r("creative-director", "Creative Direction", ["creative director", "chief creative officer"], ["Creative Vision", "Team Leadership", "Campaign Concepts", "Brand Storytelling", "Client Presentation", "Communication"], "creative director|vision|concept|campaign|leadership|story"),
  r("art-director", "Art Direction", ["art director", "senior art director"], ["Visual Direction", "Layout", "Typography", "Team Guidance", "Brand Consistency", "Communication"], "art director|visual direction|layout|typography|creative|brand"),
  r("motion-graphic-designer", "Motion Graphics", ["motion graphic designer", "motion designer", "motion graphics artist"], ["Motion Design", "Animation", "After Effects", "Storyboarding", "Timing", "Creativity"], "motion graphics|motion design|after effects|animate|kinetic"),
  r("web-designer", "Web Design", ["web designer", "website designer", "digital designer"], ["Web Layout", "Responsive Design", "Figma / XD", "Typography", "UI Polish", "Communication"], "web design|website|landing|figma|layout|responsive"),
  r("illustrator", "Illustration", ["\\billustrator\\b", "digital illustrator", "freelance illustrator"], ["Illustration Style", "Drawing", "Digital Tools", "Client Briefs", "Composition", "Creativity"], "illustration|illustrator|drawing|vector|character|art"),
  r("cinematographer-design", "Cinematography", ["cinematographer", "director of photography", "\\bdop\\b"], ["Camera Work", "Lighting", "Composition", "Shot Planning", "Equipment", "Creativity"], "cinematography|dop|camera|lighting|lens|shot|frame"),
  r("sound-designer", "Sound Design", ["sound designer", "audio designer"], ["Sound Design", "Audio Editing", "Foley", "Mixing", "Software Tools", "Creativity"], "sound design|audio|foley|sfx|mix|pro tools"),
  r("fashion-designer", "Fashion Design", ["fashion designer", "apparel designer", "textile designer"], ["Fashion Illustration", "Fabric Knowledge", "Trend Research", "Pattern Making", "Collection Planning", "Communication"], "fashion|apparel|textile|garment|trend|style"),
  r("video-editor", "Video Editing", ["video editor", "video production", "post production"], ["Video Editing", "Storytelling", "Color Grading", "Audio Sync", "Software Tools", "Creativity"], "video|edit|premiere|after effects|footage|timeline"),
  r("animator", "Animation", ["animator", "motion graphics", "2d animator", "3d animator"], ["Animation Principles", "Motion Design", "Storyboarding", "Software Tools", "Timing & Spacing", "Creativity"], "animation|motion|after effects|maya|blender|storyboard"),
  r("graphic-designer", "Graphic Design", ["graphic designer", "visual designer", "creative designer"], ["Visual Design", "Adobe Creative Suite", "Typography", "Brand Assets", "Layout", "Communication"], "graphic|photoshop|illustrator|design|visual|brand"),
  r("ui-ux-designer", "UI / UX Design", ["ui/ux", "ui ux", "ux designer", "ui designer", "product designer", "user experience designer"], ["UI Design", "UX Research", "Figma", "Prototyping", "Usability", "Communication"], "ux|ui|figma|prototype|wireframe|usability"),

  // --- Media & Entertainment ---
  r("casting-director", "Casting", ["casting director", "casting agent"], ["Talent Scouting", "Auditions", "Role Fit", "Negotiation", "Scheduling", "Communication"], "casting|audition|talent|role|selection|screen test"),
  r("talent-manager-media", "Talent Management", ["talent manager", "artist manager", "celebrity manager"], ["Career Strategy", "Contracts", "Scheduling", "Brand Deals", "Networking", "Communication"], "talent manager|artist|celebrity|booking|contract|career"),
  r("media-planner", "Media Planning", ["media planner", "media buyer", "media strategist"], ["Media Strategy", "Budget Allocation", "Channel Planning", "ROI Analysis", "Vendor Negotiation", "Communication"], "media plan|media buy|tv|radio|ooh|reach|grp"),
  r("script-supervisor", "Script Supervision", ["script supervisor", "continuity supervisor"], ["Script Continuity", "Scene Notes", "Coverage", "Attention to Detail", "Communication", "Organization"], "script supervisor|continuity|scene|take|notes|coverage"),
  r("media-production-manager", "Media Production", ["production manager film", "film production manager", "show production manager"], ["Production Scheduling", "Budget", "Crew Coordination", "Logistics", "Problem Solving", "Communication"], "production manager|shoot|crew|schedule|budget|set"),
  r("makeup-artist", "Makeup & Styling", ["makeup artist", "mua", "beauty artist"], ["Makeup Techniques", "Skin Prep", "Character Looks", "Hygiene", "Client Consultation", "Creativity"], "makeup|mua|beauty|styling|cosmetic|look"),
  r("costume-designer", "Costume Design", ["costume designer", "wardrobe stylist", "costume supervisor"], ["Costume Design", "Fabrics", "Fitting", "Period Research", "Wardrobe Management", "Creativity"], "costume|wardrobe|outfit|styling|fabric|period"),
  r("lighting-technician", "Lighting", ["lighting technician", "gaffer", "lighting assistant"], ["Lighting Setup", "Equipment", "Safety", "Scene Requirements", "Team Coordination", "Technical Skill"], "lighting|gaffer|grip|luminaire|set light|exposure"),
  r("voice-over-artist", "Voice Over", ["voice over artist", "voice actor", "voice talent"], ["Voice Control", "Diction", "Script Reading", "Recording", "Character Voices", "Communication"], "voice over|voice actor|dubbing|narration|recording|vo"),
  r("choreographer", "Choreography", ["choreographer", "dance director"], ["Choreography", "Movement Direction", "Rehearsal Planning", "Creativity", "Team Leadership", "Communication"], "choreograph|dance routine|movement|rehearsal|stage"),
  r("dancer", "Dance / Performance", ["\\bdancer\\b", "professional dancer", "ballet dancer"], ["Dance Technique", "Performance", "Discipline", "Expression", "Rehearsal", "Communication"], "dance|dancer|ballet|performance|routine|stage"),
  r("podcaster", "Podcasting", ["\\bpodcaster\\b", "podcast host", "podcast producer"], ["Content Planning", "Hosting", "Audio Production", "Guest Coordination", "Distribution", "Communication"], "podcast|audio show|episode|host|rss|spotify"),
  r("radio-jockey", "Radio / RJ", ["radio jockey", "\\brj\\b", "radio host", "radio presenter"], ["Hosting", "Voice", "Content Planning", "Audience Engagement", "Live Shows", "Communication"], "radio|rj|jockey|fm|host|on air"),
  r("tv-anchor", "TV Anchoring", ["tv anchor", "news anchor", "television presenter", "news presenter"], ["On-camera Presence", "Script Reading", "Live Reporting", "Interviewing", "Clear Delivery", "Communication"], "anchor|tv presenter|news presenter|broadcast|teleprompter"),
  r("news-anchor", "News Presentation", ["news anchor", "news reader", "bulletin anchor"], ["News Delivery", "Script Reading", "Live Broadcast", "Credibility", "Interview Skills", "Communication"], "news anchor|bulletin|headline|broadcast news|reader"),
  r("composer", "Music Composition", ["\\bcomposer\\b", "film composer", "music composer"], ["Composition", "Orchestration", "Music Theory", "DAW Tools", "Collaboration", "Creativity"], "composer|composition|score|orchestration|melody|harmony"),
  r("singer", "Singing / Vocals", ["\\bsinger\\b", "vocalist", "playback singer"], ["Vocal Technique", "Pitch & Rhythm", "Performance", "Breath Control", "Expression", "Communication"], "singer|vocal|voice|singing|melody|performance"),
  r("screenwriter", "Screenwriting", ["screenwriter", "scriptwriter", "screenplay writer"], ["Story Structure", "Dialogue", "Character Development", "Formatting", "Rewriting", "Creativity"], "screenplay|script|dialogue|story|writer|plot"),
  r("film-editor", "Film Editing", ["film editor", "video editor film", "\\beditor\\b film"], ["Editing Rhythm", "Storytelling", "Software Tools", "Color & Sound Sync", "Collaboration", "Creativity"], "film edit|editor|cut|timeline|premiere|davinci"),
  r("film-producer", "Film Production", ["film producer", "movie producer", "executive producer", "line producer"], ["Production Planning", "Budgeting", "Scheduling", "Team Coordination", "Problem Solving", "Communication"], "producer|production|budget|film|financing|crew"),
  r("photographer", "Photography", ["photographer", "photo journalist", "camera operator"], ["Composition", "Lighting", "Editing", "Equipment", "Client Direction", "Creativity"], "photo|camera|lighting|lens|shoot|edit"),
  r("journalist", "Journalism", ["journalist", "reporter", "news correspondent", "editorial"], ["Reporting", "Research", "Writing", "Fact Checking", "Interviewing", "Communication"], "journal|news|report|media|press|article"),
  r("music-producer", "Music Production", ["music producer", "sound engineer", "audio engineer"], ["Music Theory", "Production Tools", "Mixing", "Sound Design", "Creativity", "Collaboration"], "music|audio|sound|mix|production|studio"),
  r("director", "Film / Direction", ["film director", "movie director", "television director"], ["Storytelling", "Scene Composition", "Team Leadership", "Creative Vision", "Production Planning", "Communication"], "direct|film|cinema|production|script|scene|director"),
  r("actor", "Acting / Performance", ["\\bactor\\b", "actress", "performer", "voice artist"], ["Acting Technique", "Expression", "Script Understanding", "Stage Presence", "Collaboration", "Communication"], "act|performance|stage|script|drama|voice"),

  // --- Government & Law ---
  r("judge", "Judiciary", ["\\bjudge\\b", "magistrate", "judicial officer"], ["Legal Knowledge", "Judgment", "Case Analysis", "Constitutional Law", "Ethics", "Communication"], "judge|court|judgment|legal|law|bench"),
  r("ips-officer", "Police / IPS", ["ips officer", "police officer", "sub inspector", "\\bsi\\b", "constable", "law enforcement"], ["Law & Order", "Investigation", "Public Safety", "Crisis Handling", "Documentation", "Communication"], "police|ips|law enforcement|investigation|patrol|crime"),
  r("ias-officer", "Civil Services / Administration", ["ias officer", "civil services", "administrative officer", "district collector", "dm"], ["Public Administration", "Policy", "Governance", "Decision Making", "Leadership", "Communication"], "ias|civil service|administration|government|policy|governance"),
  r("army-officer", "Defense / Army", ["army officer", "army soldier", "defense officer", "military officer", "navy officer", "air force officer"], ["Discipline", "Leadership", "Physical Fitness", "Tactical Awareness", "Teamwork", "Communication"], "army|military|defense|navy|air force|soldier|officer"),
  r("railway-officer", "Railway", ["railway officer", "station master", "railway operations"], ["Rail Operations", "Safety Protocols", "Scheduling", "Customer Service", "Compliance", "Communication"], "railway|rail|train|station|operations"),
  r("public-prosecutor", "Public Prosecution", ["public prosecutor", "prosecutor"], ["Criminal Law", "Case Preparation", "Court Advocacy", "Evidence", "Legal Research", "Communication"], "prosecut|criminal|court|litigation|evidence"),
  r("advocate", "Legal Advocacy", ["\\badvocate\\b", "barrister"], ["Court Advocacy", "Legal Research", "Case Strategy", "Drafting", "Client Counseling", "Communication"], "advocate|court|litigation|pleading|bar"),
  r("lawyer", "Legal", ["\\blawyer\\b", "legal counsel", "attorney", "legal advisor"], ["Legal Research", "Contract Law", "Case Analysis", "Drafting", "Compliance", "Communication"], "legal|law|contract|litigation|counsel"),

  // --- Agriculture ---
  r("horticulture", "Horticulture", ["horticulture", "horticulturist", "floriculturist"], ["Plant Science", "Crop Planning", "Soil Management", "Pest Control", "Harvest Planning", "Communication"], "horticulture|plant|crop|soil|garden|nursery"),
  r("dairy-manager", "Dairy Management", ["dairy manager", "dairy farming", "milk production"], ["Dairy Operations", "Animal Health", "Quality Control", "Supply Chain", "Hygiene Standards", "Communication"], "dairy|milk|cattle|livestock|farm"),
  r("agriculture-officer", "Agriculture", ["agriculture officer", "agricultural officer", "extension officer"], ["Crop Management", "Soil Science", "Irrigation", "Farmer Support", "Government Schemes", "Communication"], "agriculture|crop|farmer|irrigation|soil|extension"),
  r("farmer", "Farming", ["\\bfarmer\\b", "agriculturist", "farm manager"], ["Crop Production", "Soil & Irrigation", "Equipment", "Market Awareness", "Season Planning", "Communication"], "farm|crop|agriculture|harvest|soil|irrigation"),

  // --- Aviation ---
  r("air-traffic-controller", "Air Traffic Control", ["air traffic controller", "atc"], ["Flight Coordination", "Safety Protocols", "Communication", "Quick Decisions", "Regulations", "Stress Management"], "air traffic|atc|flight control|radar|tower"),
  r("aircraft-engineer", "Aircraft Engineering", ["aircraft engineer", "aerospace engineer", "aircraft maintenance"], ["Aircraft Systems", "Maintenance", "Safety Checks", "Technical Manuals", "Troubleshooting", "Communication"], "aircraft|aerospace|aviation|maintenance|aero"),
  r("cabin-crew", "Cabin Crew", ["cabin crew", "flight attendant", "air hostess", "air steward"], ["Passenger Safety", "Customer Service", "Emergency Procedures", "Communication", "Grooming & Protocol", "Teamwork"], "cabin|flight attendant|airline|passenger|safety|service"),
  r("pilot", "Aviation / Pilot", ["\\bpilot\\b", "commercial pilot", "airline pilot", "captain"], ["Flight Operations", "Navigation", "Safety Procedures", "Decision Making", "Regulations", "Communication"], "pilot|aviation|flight|aircraft|cockpit|navigation"),

  // --- Hospitality & Tourism ---
  r("chef", "Culinary / Chef", ["\\bchef\\b", "sous chef", "head chef", "cook", "culinary"], ["Culinary Skills", "Food Safety", "Menu Planning", "Kitchen Management", "Creativity", "Communication"], "chef|cook|kitchen|culinary|food|recipe"),
  r("hotel-manager", "Hotel Management", ["hotel manager", "hospitality manager", "front office manager"], ["Guest Service", "Operations", "Team Leadership", "Revenue Management", "Quality Standards", "Communication"], "hotel|hospitality|guest|front office|rooms|service"),
  r("travel-agent", "Travel & Tourism", ["travel agent", "tour operator", "travel consultant"], ["Itinerary Planning", "Booking Systems", "Destination Knowledge", "Customer Service", "Sales", "Communication"], "travel|tour|booking|itinerary|tourism|visa"),
  r("event-manager", "Event Management", ["event manager", "event coordinator", "wedding planner"], ["Event Planning", "Vendor Management", "Budgeting", "Logistics", "Client Communication", "Problem Solving"], "event|wedding|venue|logistics|coordination|planner"),

  // --- Construction & Architecture ---
  r("interior-designer", "Interior Design", ["interior designer", "interior architect", "space planner"], ["Space Planning", "Materials", "AutoCAD / 3D", "Client Briefs", "Budgeting", "Communication"], "interior|space|furnish|decor|layout|3d"),
  r("architect", "Architecture", ["\\barchitect\\b", "architectural designer"], ["Architectural Design", "AutoCAD / Revit", "Building Codes", "Client Presentation", "Structural Coordination", "Communication"], "architect|building|design|revit|autocad|blueprint"),
  r("site-engineer-construction", "Construction Site", ["site engineer", "site supervisor", "construction supervisor"], ["Site Management", "Safety", "Quality Control", "Scheduling", "Technical Drawing", "Communication"], "site|construction|supervisor|civil|safety|labour"),

  // --- Science & Research ---
  r("biotechnologist", "Biotechnology", ["biotechnologist", "biotechnology", "bio tech"], ["Lab Techniques", "Research Methods", "Data Analysis", "Documentation", "Safety", "Communication"], "biotech|biology|lab|research|genetic|cell"),
  r("scientist", "Science / Research", ["\\bscientist\\b", "research scientist", "r&d"], ["Research Methods", "Data Analysis", "Technical Writing", "Experiment Design", "Critical Thinking", "Communication"], "research|science|experiment|lab|analysis|hypothesis"),
  r("market-research-analyst", "Market Research", ["market research analyst", "market analyst", "consumer research analyst"], ["Survey Design", "Data Analysis", "Consumer Insights", "Reporting", "Competitive Analysis", "Communication"], "market research|consumer insight|survey|segment|competitor|trend"),
  r("research-analyst", "Research Analysis", ["research analyst", "policy researcher"], ["Research Methods", "Data Collection", "Analysis", "Reporting", "Critical Thinking", "Communication"], "research|analysis|report|data|survey|insight"),

  // --- Sports & Fitness ---
  r("sports-manager", "Sports Management", ["sports manager", "sports administrator", "athletic director"], ["Team Management", "Event Planning", "Sports Marketing", "Budgeting", "Leadership", "Communication"], "sports|athletic|team|event|league|management"),
  r("fitness-trainer", "Fitness Training", ["fitness trainer", "personal trainer", "gym trainer", "fitness coach"], ["Exercise Science", "Program Design", "Client Assessment", "Nutrition Basics", "Motivation", "Communication"], "fitness|gym|trainer|workout|exercise|health"),
  r("coach", "Coaching", ["\\bcoach\\b", "head coach", "assistant coach", "sports coach"], ["Training Planning", "Performance Analysis", "Team Leadership", "Motivation", "Strategy", "Communication"], "coach|training|team|player|drill|tactics"),
  r("athlete", "Sports / Athletics", ["\\bathlete\\b", "professional player", "sportsperson"], ["Sport Technique", "Physical Fitness", "Discipline", "Performance", "Teamwork", "Communication"], "athlete|sport|fitness|game|competition|training"),

  // --- Logistics ---
  r("logistics-coordinator", "Logistics", ["logistics coordinator", "transport coordinator", "fleet coordinator"], ["Transport Planning", "Vendor Coordination", "Documentation", "Tracking", "Problem Solving", "Communication"], "logistics|transport|fleet|shipment|freight|dispatch"),
  r("warehouse-manager", "Warehouse", ["warehouse manager", "warehouse supervisor", "store keeper"], ["Inventory Control", "Warehouse Operations", "Safety", "Team Management", "WMS Systems", "Communication"], "warehouse|inventory|stock|dispatch|storage|wms"),
  r("supply-chain", "Supply Chain", ["supply chain manager", "supply chain analyst", "procurement manager"], ["Supply Planning", "Vendor Management", "Inventory", "Cost Control", "Process Improvement", "Communication"], "supply chain|procurement|vendor|inventory|logistics"),

  // --- Retail & E-commerce ---
  r("ecommerce-manager", "E-commerce", ["e-commerce manager", "ecommerce manager", "online store manager", "marketplace manager"], ["Online Catalog", "Conversion", "Order Operations", "Customer Support", "Analytics", "Communication"], "ecommerce|e-commerce|online store|marketplace|shopify|amazon"),
  r("cashier", "Retail / Cashier", ["\\bcashier\\b", "billing executive", "checkout"], ["Billing Systems", "Cash Handling", "Customer Service", "Accuracy", "POS Operations", "Communication"], "cashier|billing|pos|checkout|counter|payment"),
  r("store-manager", "Retail Management", ["store manager", "retail manager", "shop manager"], ["Store Operations", "Sales Targets", "Team Management", "Inventory", "Customer Service", "Communication"], "store|retail|shop|sales|inventory|merchandise"),

  // --- Freelance & Content ---
  r("content-writer", "Content Writing", ["content writer", "technical writer", "copywriter", "content specialist", "blog writer"], ["Writing & Grammar", "Research", "SEO Basics", "Content Strategy", "Editing", "Communication"], "content|writer|copywriting|article|blog|technical writing|editorial"),
  r("youtuber", "Content Creation / YouTube", ["\\byoutuber\\b", "content creator", "influencer", "vlogger", "social media influencer"], ["Content Strategy", "Video Production", "Audience Engagement", "Branding", "Analytics", "Communication"], "youtube|content|video|channel|subscriber|vlog|influencer"),
  r("virtual-assistant", "Virtual Assistant", ["virtual assistant", "\\bva\\b", "remote assistant"], ["Task Management", "Communication", "Tools & Software", "Organization", "Client Support", "Reliability"], "virtual assistant|remote|admin|calendar|email|support"),
  r("freelancer", "Freelance / Independent", ["\\bfreelancer\\b", "independent contractor", "consultant"], ["Client Management", "Project Delivery", "Time Management", "Communication", "Problem Solving", "Professionalism"], "freelance|contract|client|project|independent|consult"),

  // --- Data (generic) ---
  r("data-analyst", "Data Analysis", ["data analyst", "business intelligence", "bi analyst", "\\bsql\\b analyst"], ["SQL & Queries", "Data Visualization", "Reporting", "Analysis", "Dashboards", "Communication"], "data|sql|analytics|tableau|power bi|dashboard"),
];
